week2 index api keyword & back-end secure
raiy0929/taipei-day-trip-website pull request #3
Opened 2021-04-28 16:42 UTC by raiy0929

老師好 ， 我是瑞文
作業檢查網址：http://13.208.235.19:3000/

謝謝您：）

2021-04-28 17:36 UTC, cwpeng requested changes
以下是 400px 寬的螢幕，有多處和設計稿顯然完全不同，包括主視覺的背景圖，顏色，文字排列的狀況。
![13 208 235 19_3000_](https://user-images.githubusercontent.com/6104683/116447839-00118200-a88b-11eb-9d89-c271d740611a.png)

以下是 1300px 寬的螢幕，請按照設計稿在桌機和筆電的設計，中間保持 1200px 固定的主要版面，且排列成四排。
![13 208 235 19_3000_ (1)](https://user-images.githubusercontent.com/6104683/116448024-3a7b1f00-a88b-11eb-9ffb-f8de4c70c275.png)

2021-04-29 09:08 UTC, raiy0929 commented
老師 我訂正了RWD的部分
再麻煩您檢查

謝謝：）

2021-04-29 11:25 UTC, cwpeng requested changes
以下這是我看到的 360px 螢幕的版面，文字應該可以處理不用換行，搜尋框的按鈕分開了，另外預定行程的文字顏色也不太對勁。
![未命名-2](https://user-images.githubusercontent.com/6104683/116543579-9e035c00-a920-11eb-9c45-0aa8adae9a20.png)

2021-04-29 11:54 UTC, raiy0929 commented
老師 我修好搜尋鈕並再給標頭文字一點空間 大概350px才會換行了...QQ

再請老師檢查 謝謝！

2021-04-29 12:02 UTC, cwpeng approved these changes
OK. 這樣就可以嘍 :)

2021-04-29 14:06 UTC, merged